### ISSUE TITLE
Fatal error with Puppet 5.4.0

### ISSUE THREAD

**Issue by olifre** [lelutin/puppet-fail2ban#33] opened 2018-02-26 14:12 UTC
Since #26 / #31 , this module does not work with Puppet 5.4.0 anymore, while it was working fine before. 
Error is:
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, private method `load' called for Scope(Class[Fail2ban]):Puppet::Parser::Scope (file: /etc/puppetlabs/code/environments/production/modules/fail2ban/manifests/init.pp, line: 27, column: 3) on node XXXXX.XXXXX.XXXXX
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```
This is the line with `validate_legacy(`.

**Comment by olifre** [comment] 2018-02-26 14:23
I can confirm that reverting to:
3424f0d290b540701a80daebcb86fb03972adf0b
let's things work fine with Puppet 5.4.0 again. 
All puppet master and clients here are 5.4.0 exclusively, stdlib is latest version.

**Comment by lelutin** [comment] 2018-02-27 03:53
@olifre this line is about validating that $ignoreip is an array. I'm curious how you're currently calling the fail2ban module. are you defining a value for ignoreip? (I would expect a type error clearly stated though if the type was wrong.. not a weird method error)

**Comment by lelutin** [comment] 2018-02-27 04:04
ah turns out I have puppet 5.4.0 on my laptop -- seems like that version entered sid recently :)

I can reproduce the issue with a simple call of the same function:

~~~
puppet apply --modulepath=../../modules/ -e '$ignoreip=['1','2','3']; validate_legacy("Stdlib::Compat::Array", "validate_array", $ignoreip)'
~~~

runnning with `--debug` doesn't give out much more information about what's going on.

maybe one day puppet's error messages will make a minimum of sense

**Comment by lelutin** [comment] 2018-02-27 04:07
@olifre ah! I found a way to unbreak the call: if I remove the quotes around the type, then I get no error. e.g. line 27 of init.pp in this module would become:

~~~
 27   validate_legacy(Stdlib::Compat::Array, 'validate_array', $ignoreip)
~~~

I don't know yet whether this change is compatible with puppet 3.x though :S

**Comment by olifre** [comment] 2018-02-27 04:12
@lelutin That sounds reasonable! I also wondered about the quotes, they should not really help with anything. Now the main question is... Does removing the quotes in turn break older Puppet versions?

**Comment by lelutin** [comment] 2018-02-27 04:26
that's what I'm trying to figure out right now but my vagrant-livbirt is broken blah. supposedly fixed in most recent package in debian sid. *crosses fingers*

I'll run the code without the quotes on puppet 3.x in debian jessie to see what happens

**Comment by lelutin** [comment] 2018-02-27 05:23
hum the change is fine with puppet 4.8.2 in stretch but in jessie with 3.7 I'm getting an error about unknown function validate_legacy even though I I'm on the current master with no change. something's wrong

I'm wondering now if I tested the change to validate_legacy on puppet 3.x before merging. I noted in #31 that I had verified version compatibility from stdlib's readme but maybe I didn't run a test against 3.x :\

**Comment by lelutin** [comment] 2018-02-27 05:26
if I go back to before the switch to validate_legacy, then I can run the module against 3.x again.
blah this is not great.

I guess we're getting forced here to split support to 3.x in another branch -- which will then revert the change to validate_legacy as its first commit on the branch

**Comment by lelutin** [comment] 2018-02-27 05:38
I've added comments to #32 to shorten the plan to split and modernize puppet 4.x code. This issue should be resolved first when the 3.x branch is setup. the fix could be to replace all validate_ calls to puppet types for parameters

**Comment by lelutin** [comment] 2018-03-05 06:26
@olifre I've pushed some new code on master that makes it use puppet 4.x syntax and drop support for debian releases before stretch (I have no idea whether I should drop support for an older RHEL release in order to keep that release in maintenance mode only with the 2.x branch of puppet-fail2ban)

If you'd like to test whether the new code can run without fatal error or noisy deprecation warning, you can do so now with the code on master. watch out though: I plan on probably breaking API soon with regards to all example jail classes, so stay tuned for changes on master before 3.0.0 is release since you might need to adjust calls in order to follow.

**Comment by olifre** [comment] 2018-03-05 10:22
@lelutin I can confirm that:
74240c24d0de606b67deecc970906ade958b6c57
works fine with Puppet 5.4.0 here :+1: .

**Comment by lelutin** [comment] 2018-03-07 15:40
great! thanks a bunch for testing. I'll try and finish work to release 3.0.0 soon (maybe next week-end hopefully) to have a first release that supports puppet 4.x/5.x

**Closed by lelutin** 2018-03-07 15:40 UTC
Labels: puppet 3.x, puppet 4.x
