### ISSUE TITLE
Doesn't handle/purge jail.d

### ISSUE THREAD

**Issue by siliconalchemy** [lelutin/puppet-fail2ban#6] opened 2016-03-20 08:08 UTC
Some debian/ubuntu packaging of fail2ban supply a default in jail.d:
 /etc/fail2ban/jail.d/defaults-debian
```
[sshd]
enabled = true
```

This fails to start:
```
-- Unit fail2ban.service has begun starting up.
fail2ban-client[2783]: WARNING 'filter' not defined in 'sshd'. Using default one: ''
fail2ban-client[2783]: WARNING No filter set for jail sshd
fail2ban-client[2783]: WARNING 'filter' not defined in 'sshd'. Using default one: ''
fail2ban-client[2783]: ERROR  Failed during configuration: Bad value substitution: option 'action' in section 'sshd' co
systemd[1]: fail2ban.service: Control process exited, code=exited status=255
systemd[1]: Failed to start Fail2Ban Service.
```
If jail.d/defaults-debian removed, it starts fine.  Should this module manage/purge jail.d?

**Comment by lelutin** [comment] 2016-03-21 20:57
Hi there,

I believe I have not seen any jail.d directory in the debian package -- which would have been awesome to use instead of puppetlabs-concat). Also since I haven't tested the module on Ubuntu myself and haven't had user reports of success/failure yet, it wasn't added to the supported distros list.

Could you give me more info about the Ubuntu version, and maybe the fail2ban package version?

**Comment by lelutin** [comment] 2016-03-23 04:21
Ah, sorry I've just looked the jessie version of the debian package and it does indeed have a jail.d directory. I don't see a debian-defaults file, but adding a portion of manifests that helps ppl purging out this directory does make sense.

in the future I guess I'd like to use the jail.d directory and drop puppetlabs-concat entirely, so this purging will be relevant then too. however unfortunately, we'll have to keep the concat method until wheezy support is deprecated.

one way I see of how to implement such purging would be to add a new option to the fail2ban class (e.g. purge_jail_dot_d) and make it default to false. @siliconalchemy  does that sound reasonable to you?

**Comment by lelutin** [comment] 2016-03-23 05:00
hmm .. I'm pondering the idea of setting purging to true by default. when management of jails in jail.d is implemented, it would make more sense since the purging would reproduce the current behaviour that we're having with concat fragments (e.g. an unmanaged jail gets removed automatically)

**Comment by lelutin** [comment] 2016-03-23 05:32
I've pushed a branch purge_jail.d to implement this. I have still not tested it.

@siliconalchemy tell me if the commit on that branch looks sane to you.

**Comment by siliconalchemy** [comment] 2016-03-25 08:51
In config.pp:
```
if $fail2ban::purge_jail_dot_d {
    if $::osfamily == 'Debian' and $::operatingsystemmajrelease == 7 {
```
I think it should be $::operatingsystem rather than $::osfamily.  $::osfamily Debian will still be true for Ubuntu which has different versioning.

**Comment by siliconalchemy** [comment] 2016-03-25 08:56
It still fails because it's not purging, looks like you need to add recurse option:
```
      file { '/etc/fail2ban/jail.d':
        ensure => directory,
        recurse => true,
        purge  => true,
      }
```
Now it works :)

**Comment by lelutin** [comment] 2016-03-28 18:23
@siliconalchemy oops! you're totally right about those two details. thanks for your good review :)

I've pushed two commits to fix those two issues:

* 3090663
* 4e39884

If you see nothing else that seems off, I'll merge this branch with master and prepare for a release soon

**Comment by siliconalchemy** [comment] 2016-03-30 09:43
Yes seems to be working great now thanks :)

**Comment by lelutin** [comment] 2016-03-30 11:18
great! I've merged this to master and pushed to github.

thanks the help!

**Closed by lelutin** 2016-03-30 11:18 UTC
Labels: enhancement
