### ISSUE TITLE
Odd dependency issue

### ISSUE THREAD

**Issue by siliconalchemy** [lelutin/puppet-fail2ban#5] opened 2016-03-15 18:24 UTC
```
Warning: Missing dependency 'puppetlabs-concat':
  'LeLutin-fail2ban' (v1.1.0) requires 'puppetlabs-concat' (>= 1.0.0)
Warning: Missing dependency 'puppetlabs-stdlib':
  'LeLutin-fail2ban' (v1.1.0) requires 'puppetlabs-stdlib' (>= 3.0.0)
```

However I have both installed:
```
├── LeLutin-fail2ban (v1.1.0)
├── puppetlabs-concat (v2.1.0)
├── puppetlabs-stdlib (v4.11.0)
```

When applying I get this warning:
```
Warning: Scope(Concat::Fragment[jail_ssh]): The $ensure parameter to concat::fragment is deprecated and has no effect.
```

**Comment by lelutin** [comment] 2016-03-16 03:08
hmm I was able to reproduce the warnings for missing dependencies with puppet 3.7.2 (debian jessie) with concat 1.2.5 and stdlib 4.11.0

I'll see if some I can find out why that would not match


as for the warning with concat 2.x, I admit that I'm not using 2.x much so I haven't seen this one before. I'll see if the "require" lines are actually useful. if not we can remove them and hopefully that'll be the only spark with the 2.x branch

**Comment by lelutin** [comment] 2016-03-16 03:40
for the warnings about dependencies I was pointed to this bug report:
https://tickets.puppetlabs.com/browse/PUP-3121

apparently this issue with dependencies is fixed in 4.0.0. I was also told that the 3.x branch of puppet is currently only getting security patches so the fix is not planned for backporting to 3.x

I'll add a mention of this in the module's readme.

**Comment by lelutin** [comment] 2016-03-16 04:37
I've documented the module dependency bug in 84a8d0b

also the `ensure` parameter to fail2ban::jail is now deprecated, and the value is not used anymore with the concat::fragment resource. This should fix the warnings you reported. This was changed in 6d2fbac

Finally, I've bumped version to 1.2.0 because of the deprecation and tagged it. This new version was released to the forge.

Thanks for reporting those issues!

**Comment by siliconalchemy** [comment] 2016-03-16 08:24
Thanks for the warning fix, confirmed working in 1.2.0 :)

What about changing the dependencies in metadata.json as mentioned in the PUP?
```
  "dependencies": [
    {"name":"puppetlabs/stdlib","version_requirement":">= 3.0.0"},
    {"name":"puppetlabs/concat","version_requirement":">= 1.0.0"}
  ]
```
This fixes the dependency warnings for me in puppet 3.7.2

**Comment by lelutin** [comment] 2016-03-17 21:40
this could be done indeed. I was told on IRC that I should be using hiphens, but was unable to get a reason why.. also the official documentation about writing modules is using slashes for dependencies.

so I'm confused in two ways:
1) why would we use "User-Module" for the module name and then "User/Module" for dependencies
2) why am I getting conflicted info from documentation and IRC

.. I'll see if I can bug ppl about those two points cause it makes no sense. I guess the best place for this kind of question would be on the puppet-users mailing list. I'll send that question soon and let you know what responses are given (in case you're not subscribed to that mailing list -- and also for future ppl who'll read this ticket)

**Comment by lelutin** [comment] 2016-03-18 04:26
I found this doc that says User/Module is actually probably not right or it's undefined how it will be treated in the future:

https://docs.puppetlabs.com/puppet/latest/reference/modules_publishing.html#another-note-on-module-names

**Comment by lelutin** [comment] 2016-03-18 04:28
ok and I found again the documentation that's showing an example with slashes:

https://docs.puppetlabs.com/puppet/latest/reference/modules_metadata.html#specifying-dependencies

**Comment by fnoop** [comment] 2016-03-20 07:56
If slashes currently work on all versions without warning but hypens don't, maybe this is pragmatically the better way for now even if not necessarily the 'correct' way according to the latest documentation?

**Comment by siliconalchemy** [comment] 2016-03-20 08:01
If slashes currently work on all versions without warning but hypens don't, maybe this is pragmatically the better way for now even if not necessarily the 'correct' way according to the latest documentation?

**Comment by lelutin** [comment] 2016-03-20 20:14
@siliconalchemy @fnoop indeed. I've pushed c48f05e to change it to slashes.

my point in trying to find out if it's the "correct" way of doing things was to find out if puppetlabs are planning to make dependencies with slashes disappear soon.

**Comment by lelutin** [comment] 2016-03-24 23:45
comment from the discussion on the mailing list:

~~~
As for deprecation, though it is a thorn in our side, removing support for 
slashes is not on a roadmap. We do recommend always using dashes starting 
with Puppet 4.0, though.
~~~

I'll keep the dependencies with slashes until they decide to deprecate it. should keep things working ok with 3.x.

The slashes in dependencies will get into the next release. there are other issues and PRs open right now so I'll close them before releasing.

**Closed by lelutin** 2016-03-24 23:45 UTC
